#!/usr/bin/env node
/* Simulates thousands of AI drafts to build draft-grade baselines (per league size) and average draft
   position for each Pokemon. Writes js/norms.js. Run after any rating or engine change:  node scripts/build_norms.js */
const fs = require("fs"), path = require("path");
const ROOT = path.join(__dirname, "..");
const E = require(path.join(ROOT, "js/engine.js"));
const txt = fs.readFileSync(path.join(ROOT, "js/data.js"), "utf8");
const P = JSON.parse(txt.slice(txt.indexOf("{"), txt.lastIndexOf("}") + 1)).pokemon;
const byId = new Map(P.map(p => [p.id, p]));
const TYPES = [...new Set(P.flatMap(p => p.types))];
const DRAFTS = 300;

function aiDraft(n, rnd, log) {
  const teams = [...Array(n)].map(() => ({ roster: {}, style: E.STYLE_KEYS[Math.floor(rnd() * E.STYLE_KEYS.length)], fav: rnd.pick(TYPES) }));
  const taken = new Set();
  for (let pk = 0; pk < n * 22; pk++) {
    const r = Math.floor(pk / n), i = pk % n, t = r % 2 === 0 ? i : n - 1 - i;
    const c = E.aiChoose(P, teams, t, taken, { style: teams[t].style, favType: teams[t].fav, rng: rnd });
    teams[t].roster[c.slot] = c.pid; taken.add(c.pid);
    if (log) log(c.pid, pk + 1);
  }
  return teams;
}

const norms = {};
const adpSum = {}, adpCnt = {};
for (let n = 2; n <= 6; n++) {
  const rnd = E.rngFrom("norms-" + n);
  const acc = {};
  for (let d = 0; d < DRAFTS; d++) {
    const teams = aiDraft(n, rnd, n === 6 ? (pid, pick) => { adpSum[pid] = (adpSum[pid] || 0) + pick; adpCnt[pid] = (adpCnt[pid] || 0) + 1; } : null);
    for (const t of teams) {
      const g = E.groupScores(t.roster, byId);
      for (const k of Object.keys(g)) (acc[k] = acc[k] || []).push(g[k]);
    }
  }
  norms[n] = {};
  for (const k of Object.keys(acc)) {
    const a = acc[k], mu = a.reduce((x, y) => x + y, 0) / a.length;
    // floor the spread so tiny differences don't swing a whole letter grade
    const sd = Math.max(k === "TEAM" ? 1.2 : 2.5, Math.sqrt(a.reduce((x, y) => x + (y - mu) ** 2, 0) / a.length));
    norms[n][k] = [+mu.toFixed(2), +sd.toFixed(2)];
  }
}
// average draft position in 6-team leagues (undrafted counts as pick 140)
const adp = {};
for (const p of P) adp[p.id] = +(((adpSum[p.id] || 0) + (DRAFTS - (adpCnt[p.id] || 0)) * 140) / DRAFTS).toFixed(1);
fs.writeFileSync(path.join(ROOT, "js/norms.js"),
  "// Generated by scripts/build_norms.js - do not edit by hand\nwindow.G151_NORMS = " + JSON.stringify({ norms, adp }) + ";\n");
console.log("wrote js/norms.js");
console.log("6-team norms", JSON.stringify(norms[6]));
console.log("2-team norms", JSON.stringify(norms[2]));
const top = Object.entries(adp).sort((a, b) => a[1] - b[1]).slice(0, 12).map(([id, v]) => `${byId.get(+id).name} ${v}`);
console.log("top ADP", top.join(", "));
