#!/usr/bin/env node
/* Simulates thousands of AI drafts to build draft-grade baselines (per league size) and average draft
   position for each Pokemon. Writes js/norms.js. Run after any rating or engine change:  node scripts/build_norms.js */
const fs = require("fs"), path = require("path");
const ROOT = path.join(__dirname, "..");
const E = require(path.join(ROOT, "js/engine.js"));
const load = f => { const t = fs.readFileSync(path.join(ROOT, f), "utf8"); return JSON.parse(t.slice(t.indexOf("{"), t.lastIndexOf("}") + 1)).pokemon; };
// big pool: fewer simulated drafts (each pick scans ~1,000 Pokemon)
const POOLS = [{ key: "gen1", file: "js/data.js", drafts: 300 }, { key: "all", file: "js/data-all.js", drafts: 60 }];
let P, byId, TYPES, DRAFTS;

function aiDraft(n, rnd, log) {
  const teams = [...Array(n)].map(() => ({ roster: {}, style: E.STYLE_KEYS[Math.floor(rnd() * E.STYLE_KEYS.length)], fav: rnd.pick(TYPES) }));
  const taken = new Set();
  for (let pk = 0; pk < n * 22; pk++) {
    const r = Math.floor(pk / n), i = pk % n, t = r % 2 === 0 ? i : n - 1 - i;
    const c = E.aiChoose(P, teams, t, taken, { style: teams[t].style, favType: teams[t].fav, rng: rnd });
    teams[t].roster[c.slot] = c.pid; taken.add(c.pid);
    if (log) log(c.pid, pk + 1);
  }
  return teams;
}

const out = {};
for (const pool of POOLS) {
P = load(pool.file); byId = new Map(P.map(p => [p.id, p])); TYPES = [...new Set(P.flatMap(p => p.types))]; DRAFTS = pool.drafts;
const t0 = Date.now();
const norms = {};
const adpSum = {}, adpCnt = {};
for (let n = 2; n <= 6; n++) {
  const rnd = E.rngFrom((pool.key === "gen1" ? "" : pool.key + "-") + "norms-" + n);
  const acc = {};
  for (let d = 0; d < DRAFTS; d++) {
    const teams = aiDraft(n, rnd, n === 6 ? (pid, pick) => { adpSum[pid] = (adpSum[pid] || 0) + pick; adpCnt[pid] = (adpCnt[pid] || 0) + 1; } : null);
    for (const t of teams) {
      const g = E.groupScores(t.roster, byId);
      for (const k of Object.keys(g)) (acc[k] = acc[k] || []).push(g[k]);
    }
  }
  norms[n] = {};
  for (const k of Object.keys(acc)) {
    const a = acc[k], mu = a.reduce((x, y) => x + y, 0) / a.length;
    // floor the spread so tiny differences don't swing a whole letter grade
    const sd = Math.max(k === "TEAM" ? 1.2 : 2.5, Math.sqrt(a.reduce((x, y) => x + (y - mu) ** 2, 0) / a.length));
    norms[n][k] = [+mu.toFixed(2), +sd.toFixed(2)];
  }
}
// average draft position in 6-team leagues (undrafted counts as one pick past the last)
const adp = {};
const last = 6 * 22 + 8;
for (const p of P) if (adpCnt[p.id]) adp[p.id] = +(((adpSum[p.id] || 0) + (DRAFTS - adpCnt[p.id]) * last) / DRAFTS).toFixed(1);
out[pool.key] = { count: P.length, norms, adp };
const top = Object.entries(adp).sort((a, b) => a[1] - b[1]).slice(0, 10).map(([id, v]) => `${byId.get(+id).name} ${v}`);
console.log(`${pool.key}: ${P.length} Pokemon, ${DRAFTS} drafts per league size, ${((Date.now() - t0) / 1000).toFixed(1)}s. Top ADP: ${top.join(", ")}`);
}
fs.writeFileSync(path.join(ROOT, "js/norms.js"),
  "// Generated by scripts/build_norms.js - do not edit by hand\nwindow.G151_NORMS = " + JSON.stringify(out) + ";\n");
console.log("wrote js/norms.js");
