#!/usr/bin/env python3
"""
Build supabase/setup.sql = supabase/schema.sql + the current ratings and roster spots.
Run after build_data.py whenever ratings change, then re-run setup.sql in the Supabase SQL Editor.
"""
import json, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# roster spots -> rating position (must match SLOTS in js/app.js)
SLOTS = {
    "QB": "QB", "RB": "RB", "WR1": "WR", "WR2": "WR", "WR3": "WR", "TE": "TE",
    "LT": "OL", "LG": "OL", "C": "OL", "RG": "OL", "RT": "OL",
    "LDE": "DL", "LDT": "DL", "RDT": "DL", "RDE": "DL",
    "WLB": "LB", "MLB": "LB", "SLB": "LB",
    "CB1": "CB", "CB2": "CB", "FS": "S", "SS": "S",
}


def main():
    data = json.load(open(os.path.join(ROOT, "data", "pokemon.json")))["pokemon"]
    schema = open(os.path.join(ROOT, "supabase", "schema.sql")).read()
    slots = ",\n".join(f"  ('{s}', '{p}')" for s, p in SLOTS.items())
    ratings = ",\n".join(f"  ({p['id']}, '{pos}', {v})" for p in data for pos, v in p["posOvr"].items())
    types = ",\n".join(f"  ({p['id']}, array[{', '.join(repr(t) for t in p['types'])}])" for p in data)
    seed = f"""
-- ---------- ratings and roster spots (generated by scripts/build_sql.py) ----------
delete from public.g151_slots;
insert into public.g151_slots (slot, pos) values
{slots};

delete from public.g151_ratings;
insert into public.g151_ratings (pid, pos, ovr) values
{ratings};

delete from public.g151_pokemon;
insert into public.g151_pokemon (pid, types) values
{types};
"""
    out = os.path.join(ROOT, "supabase", "setup.sql")
    with open(out, "w") as f:
        f.write(schema.rstrip() + "\n" + seed)
    print("wrote", out, f"({len(data)} pokemon, {len(SLOTS)} slots)")


if __name__ == "__main__":
    main()
