#!/usr/bin/env python3
"""
Build supabase/setup.sql = supabase/schema.sql + the current ratings and roster spots.
Run after build_data.py whenever ratings change, then re-run setup.sql in the Supabase SQL Editor.
"""
import json, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# roster spots -> rating position (must match SLOTS in js/app.js)
SLOTS = {
    "QB": "QB", "RB": "RB", "WR1": "WR", "WR2": "WR", "WR3": "WR", "TE": "TE",
    "LT": "OL", "LG": "OL", "C": "OL", "RG": "OL", "RT": "OL",
    "LDE": "DL", "LDT": "DL", "RDT": "DL", "RDE": "DL",
    "WLB": "LB", "MLB": "LB", "SLB": "LB",
    "CB1": "CB", "CB2": "CB", "FS": "S", "SS": "S",
}


POOLS = [("gen1", "pokemon.json"), ("all", "pokemon-all.json")]


def main():
    schema = open(os.path.join(ROOT, "supabase", "schema.sql")).read()
    slots = ",\n".join(f"  ('{s}', '{p}')" for s, p in SLOTS.items())
    ratings, types, counts = [], [], []
    for key, fname in POOLS:
        data = json.load(open(os.path.join(ROOT, "data", fname)))["pokemon"]
        counts.append(f"{key} {len(data)}")
        ratings += [f"('{key}',{p['id']},'{pos}',{v})" for p in data for pos, v in p["posOvr"].items()]
        types += [f"('{key}',{p['id']},array[{','.join(repr(t) for t in p['types'])}])" for p in data]
    # several rows per line keeps the file small enough to paste into the SQL Editor
    chunk = lambda rows, k: ",\n".join(",".join(rows[i:i + k]) for i in range(0, len(rows), k))
    seed = f"""
-- ---------- ratings and roster spots (generated by scripts/build_sql.py) ----------
delete from public.g151_slots;
insert into public.g151_slots (slot, pos) values
{slots};

insert into public.g151_ratings (pool, pid, pos, ovr) values
{chunk(ratings, 9)};

insert into public.g151_pokemon (pool, pid, types) values
{chunk(types, 6)};

analyze public.g151_ratings;
analyze public.g151_pokemon;
"""
    out = os.path.join(ROOT, "supabase", "setup.sql")
    with open(out, "w") as f:
        f.write(schema.rstrip() + "\n" + seed)
    print("wrote", out, f"({', '.join(counts)}; {os.path.getsize(out) // 1024} KB)")


if __name__ == "__main__":
    main()
